name: todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  build_runner: ^2.16.1
  dio: ^5.11.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_localizations: # Обязательно
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  freezed: ^4.0.2
  freezed_annotation: ^3.1.0
  go_router: ^17.3.0
  hooks_riverpod: ^3.3.2
  intl: ^0.20.3
  json_annotation: ^4.12.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-300-latin.ttf
          weight: 300
        - asset: assets/fonts/Unbounded-300-cyrillic.ttf
          weight: 300
        - asset: assets/fonts/Unbounded-400-latin.ttf
          weight: 400
        - asset: assets/fonts/Unbounded-400-cyrillic.ttf
          weight: 400
        - asset: assets/fonts/Unbounded-500-latin.ttf
          weight: 500
        - asset: assets/fonts/Unbounded-500-cyrillic.ttf
          weight: 500
        - asset: assets/fonts/Unbounded-600-latin.ttf
          weight: 600
        - asset: assets/fonts/Unbounded-600-cyrillic.ttf
          weight: 600
        - asset: assets/fonts/Unbounded-700-latin.ttf
          weight: 700
        - asset: assets/fonts/Unbounded-700-cyrillic.ttf
          weight: 700
